# This is a basic workflow to help you get started with Actions
# Credits: FunkinDroidTeam for their workflow, basically based on their workflows lmao

name: Android Build CI

# Controls when the workflow will run
on: [pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildAndroid:
    name: buildAndroid
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e
      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.2
      - name: Setup gradle.properties
        uses: SimonMarquis/ci-gradle-properties-action@v1
        with:
           path: .github/gradle.properties
      - name: Setup build.gradle
        uses: thecodemonkey/action-get-gradle-version@v1.0
        with:
          file: .github/build.gradle
      # - name: Setup Haxe Environment
      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.1.5
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: Install Libraries
        run: |
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib --never install flixel 4.9.0 --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install hscript
          haxelib install newgrounds 1.3.0
          haxelib git polymod https://github.com/larsiusprime/polymod.git f3c0320aa51c848318934c2893ed78f42b7de74c
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git extension-webm https://github.com/Sirox228/extension-webm
          haxelib git extension-androidtools https://github.com/a-random441/extension-androidtools.git c0f09f2399780091de02eb40caf5ac4f695f9cac
          haxelib install actuate 
          haxelib list
      # For Compiling to Work, do this
      - name: Configure Android
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Install HXCPP and Rebuild it
        run: |
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git
          haxelib run lime rebuild hxcpp
      # Compiles Build via Lime
      - name: Compile
        run: |
          haxelib run lime build android
          
      - uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/debug
          
